version: "3.7"
services:
    angular-app:
       container_name: front-end
       image: front-end
       build: .
       depends_on:
        - server
       ports:
           - "4200:80"
networks:
    default:
        external: true
        name: network-jenkins

