#----------------------
### STAGE 1: BUILD ###
#---------------------

# Building node from LTS version
FROM node:12.14 as build

# set working directory
WORKDIR /build

# add `/app/node_modules/.bin` to $PATH
ENV PATH /node_modules/.bin:$PATH

# Copying all necessary files required for npm install

COPY package*.json ./

# Install npm dependencies in a different folder to optimize container build process

RUN npm install && npm install -g @angular/cli

# Copying application code to container application directory
COPY . .

# Building the angular app
# RUN ng build --configuration production --output-path=/dist
RUN ng build --prod --output-path docs --base-href ng-karaoke


#--------------------------------------------------
### STAGE 2: Setup nginx and Deploy application ###
#--------------------------------------------------
#FROM nginx:alpine

## Copy defualt nginx configuration file>

#COPY --from=build ./dist /usr/share/nginx/html

#COPY ./nginx/nginx-custom.conf /etc/nginx/conf.d/default.conf

ENV TZ="America/Costa_Rica"

# expose port 80
EXPOSE 80

# CMD ["nginx","-g","daemon off;"]
# When the container starts, replace the env.js with values from environment variables
 CMD ["ng",  "serve"]
 